export const INIT_USER_DETAIL = 'INIT_USER_DETAIL';
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS';
export const ADD_ONE_SESS = 'ADD_ONE_SESS';
export const INIT_VISITOR_DETAIL = 'INIT_VISITOR_DETAIL';
export const DEL_VISITOR_DETAIL = 'DEL_VISITOR_DETAIL';

